// <auto-generated />
using dotbot.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace dotbot.Migrations
{
    [DbContext(typeof(DotbotDb))]
    [Migration("20171209043817_AddImageTable")]
    partial class AddImageTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("dotbot.Core.Definition", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Def");

                    b.HasKey("Id");

                    b.ToTable("Defs");
                });

            modelBuilder.Entity("dotbot.Core.Email", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailAddress");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("dotbot.Core.Image", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FilePath");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("dotbot.Core.UserLocation", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<int>("CityId");

                    b.Property<double>("Lat");

                    b.Property<double>("Lng");

                    b.Property<string>("TimeZone");

                    b.HasKey("Id");

                    b.ToTable("UserLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
